spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: tiny
    password: QWERDF123456
    url: jdbc:mysql://lzlz.site:3306/tiny-service?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379